### ISSUE TITLE
Clone resources to assign/soln directories

### ISSUE THREAD

**Issue by coatless** [coatless/assignr#3]
Clone any images files in `hw**-main` directory to all locations where the Rmd file is made.

**Comment by daviddalpiaz** [comment]
So I finally decided to use `assignr` instead of my hacked together script. Currently running into this issue. Also, cannot simply add the files to the assign/soln directories as it seems they are being deleted and re-created?

Edit: Fixing isn't mission critical, I do have a workaround. Just noting that there are still users.

**Comment by coatless** [comment]
@daviddalpiaz tried a lazy approach in #11. 

Try it out with:

```r
if(!requireNamespace('remotes')) install.packages('remotes')

remotes::install_github('r-assist/assignr@file-dependencies')
```

Idea: any files in `hw_dir` of `hw_dir/hw00-main.Rmd` should automatically get moved into the build directory.

**Comment by daviddalpiaz** [comment]
Hmmm. That didn't seem to do the trick. Files don't appear to be copied to assign/soln directories.

**Comment by coatless** [comment]
@daviddalpiaz re-install using the above steps. 

I'm now using the full file paths whereas before I was just selecting only the file name to determine dependencies. 

https://github.com/r-assist/assignr/pull/11/commits/017b9c28d01e94b9bc1d65f027d17c4fed943ac5

**Comment by daviddalpiaz** [comment]
Perfect. Thanks!
